# prometheus for node exporter full(grafana ID 1860), Import via grafana.com
# default global settings
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Set the evaluation interval to every 15 seconds. Default is every 1 minute.
  external_labels:
    monitor: "aims-monitor"

rule_files:
  # - "first.rules"

#set endpoint server for monitoring
scrape_configs:
  - job_name: "aims-prometheus"
    #scrape_interval: 10s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node_exeporter"
    static_configs:
      - targets: ["node-exporter:9100", "172.17.0.5:8080"]
      #- targets: ['172.17.0.5:9100','172.17.0.4:9100', '172.17.0.6:8080', '172.17.0.6:9100']

  - job_name: "docker-container"
    static_configs:
      - targets: ["cadvisor:8080"]

  #- job_name: "rabbitmq-overview"
  #  scrape_interval: 10s
  #  static_configs:
  #    - targets: ["aims-rabbitmq:15692"]
  #      labels:
  #        namespace: "production-rabbitmq"
